package fun                                                                                                                                                                                                                              ;
public  class  Fun                                                                                                                                                                                                                         {
        public static  void   main                                                                                                                                                                                                              (String args[]){
               return                                                                                                                                                                                                                               ;}
        public static  void   start                                                                                                                                                                                                             (){
               System                                                                                                                                                                                                                          .
               console                                                                                                                                                                                                                         ().
               writer                                                                                                                                                                                                                          ().
               println                                                                                                                                                                                                                         ("""
               Hello   World!                                                                                                                                                                                                                    """.replaceAll("   ", " "));
               return                                                                                                                                                                                                                           ;}
        static                                                                                                                                                                                                                               {
               start                                                                                                                                                                                                                            ();}}